### ISSUE TITLE
BUG: Giving clues to watson adds to the step count

### ISSUE THREAD

**Issue by vitorebom** [SkyBouncer/clue_step_tracker#1]
I went to Watson with an elite clue (which he already had one), an easy, medium and hard.
I gave watson the 3 clues he didn't have and the elite clue step counter shown by the plugin went up
I received a master and then gave him the elite clue, the master clue step counter of the plugin went up by 1
I haven't received another elite clue yet, but I'm assuming when I get it, the plugin will show me it had steps completed because of what happened at Watson.
When I right click "check steps" on the master clue, it reset back to 0

**Comment by YvesW** [comment]
Can confirm giving clues to Watson does increase often times increase the step count. I always receive master clues with 2-3 steps completed from him according to the plugin, and untouched clues in my bank also have several completed steps according to the plugin.

**Comment by SkyBouncer** [comment]
Oh, that is a case I did not think about.
Thanks for reporting, I'll work on a fix soon :)
The master clue starting on 2 - 3 makes sense from my code, but the elite incrementing is wierd.

**Comment by jevonsp** [comment]
Hi I hate to bother you, love the plugin, but find this to be a very annoying feature. 

any chance a fix could be made?

**Comment by SkyBouncer** [comment]
I recently got back into the game, and I'll try to fix this. Hopefully done during the weekend

**Comment by SkyBouncer** [comment]
The plugin is updated, the issue should be fixed. Let me know if there are still issues!
