### ISSUE TITLE
Add an option to show possible number of steps remaining

### ISSUE THREAD

**Issue by ChaoticElements** [SkyBouncer/clue_step_tracker#2]
I'm super dumb, and can never remember what the possible ranges of steps are for each tier of clue.

Would it be possible to add an option to show the range of steps remaining as well as the number of steps completed?

Perhaps have it appear as like
2/3-5, in a smaller font than it is so it's not so intrusive

heck, even just having an option to just show the step ranges would really help me out.

Thanks!

**Comment by SkyBouncer** [comment]
Good idea, I'll implement it!

**Comment by SkyBouncer** [comment]
The plugin is updated, the step counter now changes color based on how close you are to completion. Does this suffice, or du you still want a toggle to display the step range for each clue?

**Comment by ChaoticElements** [comment]
This looks great! Probably a better solution than including the possible number of steps remaining, it's way less clutter.

Thanks!
