### ISSUE TITLE
master clue jorral strange device

### ISSUE THREAD

**Issue by pkadep** [SkyBouncer/clue_step_tracker#5]
I had just finished a Falo step and got the jorral step.
As I was standing at Falo and hitting the strange device, it gave me 2 possible locations, macgruber woods and seer's village.
Neither was correct, it was north of sincliar mansion. 

Plugin couldn't figure it out while I was standing next to Falo.

**Comment by evilgenious448** [comment]
This is unrelated to the Clue Step Tracker plugin, but instead would be an issue with Clue Scroll, a plugin native to Runelite. You should report this issue here:
https://github.com/runelite/runelite/issues
